spring:
  profiles:
    active: prod

---
spring:
  profiles: local

custom:
  title: "local title"

---
spring:
  profiles: prod

custom:
  title: "prod title"

# yaml 에서는 블록처리를 --- 로 합니다.
# 첫번째 블록에서 어떤 프로파일을 활성화 할 것 인지 설정
# 두번쨰 블럭에서는 local profile 설정
# 세번째 블럭에서는 prod profile 설정
# 위와 같이 블록처리하면 하나의 application.yml에서 active 를 변경하는 것으로 프로파일 활성화를 변경 할 수 있습니다.